name: 'Unity Test Report'
description: 'Analyze Unity Test Report and publish results'
# ToDo Branding?
inputs:
  githubToken:
    description: 'GITHUB_TOKEN'
    required: true
  report:
    description: 'unity test report xml file to analyze'
    required: true
  workdirPrefix:
    description: 'prefix on build machine to ignore in report'
    required: false
    default: ''
  checkName:
    description: 'check name for test reports'
    required: false
    default: 'Test Report'
  failOnTestFailures:
    description: 'fail run if there were test failures'
    required: false
    default: 'false'
  failIfNoTests:
    description: 'fail run if there were no test results found'
    required: false
    default: 'true'
outputs:
  time:
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
