name: 'Unity Test Report'
description: 'Analyze Unity Test Report and publish results'
# ToDo Branding?
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
  report:
    description: 'unity test report xml file to analyze'
    required: true
    # ToDo Default?
  fail_on_test_failures: # ToDo
    description: 'fail run if there were test failures'
    required: false
    default: 'false'
  fail_if_no_tests: # ToDo
    description: 'fail run if there were no test results found'
    required: false
    default: 'true'
outputs: # ToDo
  time: # output will be available to future steps
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
